---
java_package: openjdk-11-jdk
kafka_version: "3.8.1"
kafka_scala_version: "2.13"
kafka_url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
kafka_home: "/opt/kafka" 
java_home: /usr/lib/jvm/java-11-openjdk-amd64
kafka_user: kafka
kafka_group: kafka
kafka_network_name: kafka_network
