---
system_packages:
  - curl
  - tar
  - wget
  - net-tools
  - unzip
  - python3
  - python3-pip

java_package: openjdk-11-jdk
java_home: /usr/lib/jvm/java-11-openjdk-amd64

kafka_user: kafka
kafka_group: kafka
