---
all:
  vars:
    ansible_user: kafka
    ansible_ssh_private_key_file: ./kafkakey
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    kafka_cluster:
      children:
        zookeeper:
          hosts:
            zookeeper1:
              ansible_host: "your_host"
              zookeeper_id: 1
            zookeeper2:
              ansible_host: "your_host"
              zookeeper_id: 2
            zookeeper3:
              ansible_host: "your_host"
              zookeeper_id: 3
        kafka_brokers:
          hosts:
            kafka1:
              ansible_host: "your_host"
              broker_id: 1
            kafka2:
              ansible_host: "your_host"
              broker_id: 2
            kafka3:
              ansible_host: "your_host"
              broker_id: 3
            # kafka4:
            #   ansible_host: "your_host"
            #   broker_id: 4
        kafka_ui:
          hosts:
            kafka-ui:
              ansible_host: "your_host"
