---
all:
  vars:
    ansible_user: kafka
    ansible_ssh_private_key_file: ./kafka
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    kafka_cluster:
      children:
        zookeeper:
          hosts:
            zookeeper1:
              ansible_host: 158.160.60.245
              zookeeper_id: 1
            zookeeper2:
              ansible_host: 158.160.49.196
              zookeeper_id: 2
            zookeeper3:
              ansible_host: 158.160.49.220
              zookeeper_id: 3
        kafka_brokers:
          hosts:
            kafka1:
              ansible_host: 158.160.57.42
              broker_id: 1
            kafka2:
              ansible_host: 158.160.57.165
              broker_id: 2
            kafka3:
              ansible_host: 158.160.42.192
              broker_id: 3
            kafka4:
              ansible_host: 84.201.132.161
              broker_id: 4
        kafka_ui:
          hosts:
            kafka-ui:
              ansible_host: 158.160.57.217
