---
kafka_version: "3.5.1"
kafka_scala_version: "2.13"
kafka_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"

kafka_home: /opt/kafka
kafka_data_dir: /var/lib/kafka
kafka_log_dir: /var/log/kafka

kafka_broker_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
kafka_listeners: "INTERNAL://:9093,EXTERNAL://:9092"
kafka_advertised_listeners: "INTERNAL://{{ ansible_host }}:9093,EXTERNAL://{{ ansible_host }}:9092"
kafka_inter_broker_listener_name: INTERNAL
kafka_listener_security_protocol_map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

kafka_zookeeper_connect: "{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_host'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
kafka_default_replication_factor: 3
kafka_min_insync_replicas: 2
kafka_auto_create_topics_enable: "true"
kafka_delete_topic_enable: "true"
kafka_num_partitions: 8
kafka_log_retention_hours: 168

