---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags: common

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: true
  become: true
  vars:
    system_packages:
      - openjdk-11-jdk
      - curl
      - tar
      - wget
      - net-tools
      - unzip
      - python3
      - python3-pip
      - ca-certificates
      - gnupg
      - apt-transport-https
  tags: common

- name: Set JAVA_HOME
  lineinfile:
    path: /etc/environment
    line: "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
    state: present
  become: true
  tags: common
